### ISSUE TITLE
[improvement] add unit tests to be run with `go test`

### ISSUE THREAD

**Issue by ryandeivert** [OktaSecurityLabs/sgt#11]
### Background

There are currently no unit tests for any packages. Unit tests should be added to provide better insight into regressions, identify areas for improvement, etc.

### Requested Changes

Add unit tests for packages. It might be helpful to identify which packages are of the most importance and focus on them first.

**Comment by chaimsanders-okta** [comment]
We have no plans to continue updating SGT moving forward. Please feel free to clone/fork this project, or try Kolide Fleet as an alternative (https://www.kolide.com/fleet/).
