### ISSUE TITLE
[Feature Request] Add ability upscale ec2 after new binary created

### ISSUE THREAD

**Issue by mattjane-okta** [OktaSecurityLabs/sgt#17]
## Change requested

Add ability for the autoscaling group to upscale to launch new instances when a new binary (eg update) is created.  ASG should scale to double size, wait for new instances, then scale back to original size.

**Comment by chaimsanders-okta** [comment]
We have no plans to continue updating SGT moving forward. Please feel free to clone/fork this project, or try Kolide Fleet as an alternative (https://www.kolide.com/fleet/).
