### ISSUE TITLE
[improvement] vendor dependencies using `govendor`

### ISSUE THREAD

**Issue by ryandeivert** [OktaSecurityLabs/sgt#3]
### Background

Ever-changing external dependencies are difficult to rely on, so I'd suggest vendoring all dependencies so you do not have to worry about breaking changes from third party packages.

### Requested Change(s)
Possible solution is to use [govendor](https://github.com/kardianos/govendor) or similar to vendor all third party packages. See the repo and [whitepaper](https://github.com/kardianos/govendor/blob/master/doc/whitepaper.md) for more info on how to accomplish this and the various other benefits not mentioned here.

There may be other/better ways to solve this also.

**Comment by mattjane-okta** [comment]
Resolves https://github.com/OktaSecurityLabs/sgt/pull/27
