### ISSUE TITLE
[Feature Request] Support multiple environments in same AWS account

### ISSUE THREAD

**Issue by securityclippy** [OktaSecurityLabs/sgt#32]
currently most names of terraform resources are not interpolating for an environment variable.  Adding this would fix 90% of the isssue

the other 10% is making dynamodb tables use  the env prefix as well.

**Comment by chaimsanders-okta** [comment]
We have no plans to continue updating SGT moving forward. Please feel free to clone/fork this project, or try Kolide Fleet as an alternative (https://www.kolide.com/fleet/).
