### ISSUE TITLE
[Improvement] Create reverse proxy to handle authentication to Kibana

### ISSUE THREAD

**Issue by securityclippy** [OktaSecurityLabs/sgt#5]
AWS Elasticsearch service only allows auth via AWS  auth4 or ipaddress.  To allow access to  Kibana via username/password or session token, a proxy needs to be created to handle auth.

https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-set-up-simple-proxy.html

**Comment by mattjane-okta** [comment]
resolved by https://github.com/OktaSecurityLabs/sgt/pull/61
