### ISSUE TITLE
Post-deployment documentation

### ISSUE THREAD

**Issue by jmargeotes** [OktaSecurityLabs/sgt#53]
Hello! I've successfully deployed SGT following the deployment documentation, but am a little confused on what the next steps are/how to proceed from here. Would you be able to provide some documentation on that front? Thanks!

**Comment by chaimsanders-okta** [comment]
We have no plans to continue updating SGT moving forward. Please feel free to clone/fork this project, or try Kolide Fleet as an alternative (https://www.kolide.com/fleet/).
