### ISSUE TITLE
Move config files back to config bucekt

### ISSUE THREAD

**Issue by mattjane-okta** [OktaSecurityLabs/sgt#65]
At some point it appears there was a regression to storing the config files for the ec2 instances in the log bucket.

These files should be stored in teh s3 config bucket.

**Comment by chaimsanders-okta** [comment]
We have no plans to continue updating SGT moving forward. Please feel free to clone/fork this project, or try Kolide Fleet as an alternative (https://www.kolide.com/fleet/).
