### ISSUE TITLE
[Feature Request] Redo CLI to support chained flag and better naming

### ISSUE THREAD

**Issue by securityclippy** [OktaSecurityLabs/sgt#72]
**Is your feature request related to a problem? Please describe.**
Deploying could be much clearer if flags were dependent on each other.  Depending on usage of elasticsearch, it can often be difficult to know which component to pick.

**Describe the solution you'd like**
Chain a set of flags to allow only viable options to be selected, with useful help documentation for each flag

**Comment by chaimsanders-okta** [comment]
We have no plans to continue updating SGT moving forward. Please feel free to clone/fork this project, or try Kolide Fleet as an alternative (https://www.kolide.com/fleet/).
