### ISSUE TITLE
Unsupported URL when downloading 

### ISSUE THREAD

**Issue by willo35** [OktaSecurityLabs/sgt#82]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chaimsanders-okta** [comment]
We have no plans to continue updating SGT moving forward. Please feel free to clone/fork this project, or try Kolide Fleet as an alternative (https://www.kolide.com/fleet/).
